config/routes.rb
TracerStudy::Application.routes.draw do
  

  resource :passwords  
  #  get "passwords/edit"
  #  get "passwords/update"
  get "dashboards/index"

  resource :profiles
  resources :profiles
  resources :dashboards
  authenticated :user do
    root :to => 'dashboards#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  #  as :member do
  #    get 'password/edit' => 'devise/registrations#edit', :as => 'member_edit_password'   
  #    put 'password' => 'devise/registrations#update', :as => 'member_user_password'            
  #  end
  resources :users do
    collection do
      get :reset_password
      get :verifikasi
      get :proses
    end
  end
  get "users/:id/reset_password" => "users#reset_password", :as => 'user_reset_password'
  #get "users/verifikasi" => "users#verifikasi", :as => 'user_verifikasi_alumni'
  post "users/proses" => "users#proses", :as => 'user_proses'
  get "admin/users/:id/reset_password" => "admin/users#reset_password", :as => 'admin_user_reset_password'
  get "admin/users/:id/aproval" => "admin/users#aproval", :as => 'admin_user_aproval'
  get "admin/users/:id/unaproval" => "admin/users#unaproval", :as => 'admin_user_unaproval'
  match 'profiles/edit' => 'profiles#edit', :via => :get
  
  namespace :admin do
    resources :dashboards 
    resources :profiles
    resources :cards
    resources :books do
      collection do
        get :download
      end
    end
    resources :users do
      collection do
        get :reset_password
        get :aproval
        get :all_approval
        get :unaproval
      end
    end
  end
  get "admin/books/download/:id" => "admin/books#download", :as => 'admin_book_download_xls'
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_filter :authenticate_user!
  def index
    @profiles = Profile.where(:approved => true).order('tahun_wisuda ASC')
  end
  
  def show
    @profile = Profile.find_by_tahun_wisuda(params[:id])
  end
  
  def download
    @profile = Profile.find_by_tahun_wisuda(params[:id])
    filename =  "Data-Wisuda-Tahun-#{params[:id]}.xls"
    
    respond_to do |format|
      format.html {}
      format.xls { headers["Content-Disposition"] = "attachment; filename=\"#{filename}\"" }
    end
  end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
  def space(x)
    x.times do |i|
      '&nbsp;'
    end
  end
end

app/views/admin/books/download.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
    <Worksheet ss:Name="Sheet1">
        <Table>
            <Row>
                <Cell><Data ss:Type="String">Nama Lengkap</Data></Cell>
                <Cell><Data ss:Type="String">Tempat /Tanggal Lahir</Data></Cell>
                <Cell><Data ss:Type="String">NIM</Data></Cell>
                <Cell><Data ss:Type="String">Konsentrasi</Data></Cell>
                <Cell><Data ss:Type="String">Keahlian</Data></Cell>
                <Cell><Data ss:Type="String">Nama Orang Tua</Data></Cell>
                <Cell><Data ss:Type="String">Alamat Asal</Data></Cell>
                <Cell><Data ss:Type="String">Nomor Telepon</Data></Cell>
                <Cell><Data ss:Type="String">Lokasi PKL</Data></Cell>
                <Cell><Data ss:Type="String">Judul LTA</Data></Cell>
            </Row>
            <% Concentration.find(:all).each do |konsentrasi| %>
              <% if Profile.where(:approved => true).where("concentration_id = ?", "#{konsentrasi.id}").where("tahun_wisuda = ?", "#{@profile.tahun_wisuda}").size != 0 %>
                <% Profile.where(:approved => true).where("concentration_id = #{konsentrasi.id}").where("tahun_wisuda = ?", "#{@profile.tahun_wisuda}").order("nim ASC").each do |x| %>
                  <Row>
                      <Cell><Data ss:Type="String"><%= x.nama %></Data></Cell>
                      <Cell><Data ss:Type="String"><%= x.tempat_lahir %>, <%= x.tanggal_lahir %></Data></Cell>
                      <Cell><Data ss:Type="String"><%= x.nim %></Data></Cell>
                      <Cell><Data ss:Type="String"><%= x.concentration.title %></Data></Cell>
                      <Cell><Data ss:Type="String"><%= x.keahlian %></Data></Cell>
                      <Cell><Data ss:Type="String"><%= x.ortu %></Data></Cell>
                      <Cell><Data ss:Type="String"><%= x.alamat_rumah %></Data></Cell>
                      <Cell><Data ss:Type="String"><%= x.nomor_telp %></Data></Cell>
                      <Cell><Data ss:Type="String"><%= x.tempat_pkl %></Data></Cell>
                      <Cell><Data ss:Type="String"><%= x.judul_ta %></Data></Cell>
                  </Row>
                <% end %>
              <% end %>
            <% end %>
        </Table>

    </Worksheet>
</Workbook>

app/views/admin/books/index.html.erb
<div class="page-header">
    <h3>Data Wisuda</h3>
</div>
<table class="table table-bordered responsive datatables">
    <thead>
        <tr>
            <th class="span1">Tahun Wisuda</th>
            <th class="span5">Jumlah Peserta</th>
            <th class="span2"></th>
        </tr>
    </thead>
    <tbody>
        <% n = 0 %>
        <% @profiles.each do |x| %>
          <% masuk = x.tahun_wisuda %>
          <% if n != masuk %> 
            <tr>
                <td class="span1"><%= masuk %></td>
                <td class="span5">
                    <%= Profile.where(:approved => true).where("tahun_wisuda = ?", "#{masuk}").size %> Peserta, terdiri dari :<br />
                    <% Concentration.find(:all).each do |konsentrasi| %>
                      <% if Profile.where(:approved => true).where("concentration_id = ?", "#{konsentrasi.id}").where("tahun_wisuda = ?", "#{masuk}").size != 0 %>
                        - <%= konsentrasi.title %> : <%= Profile.where(:approved => true).where("concentration_id = ?", "#{konsentrasi.id}").where("tahun_wisuda = ?", "#{masuk}").size %> Mahasiswa (NIM : <%=  Profile.where(:approved => true).where("concentration_id = ?", "#{konsentrasi.id}").where("tahun_wisuda = ?", "#{masuk}").first.nim %> s/d <%=  Profile.where(:approved => true).where("concentration_id = ?", "#{konsentrasi.id}").where("tahun_wisuda = ?", "#{masuk}").last.nim %>)<br />
                      <% end %>
                    <% end %>
                </td>
                <td class="span2"><%= link_to('<i class="glyphicon-cloud-download">Tampil</i>'.html_safe, admin_book_path(x.tahun_wisuda), :class => 'btn btn-primary') %>&nbsp;<%= link_to('<i class="glyphicon-cloud-download">Download</i>'.html_safe, admin_book_download_xls_path(masuk, format: "xls"), :class => 'btn btn-primary') %></td>
            </tr>
            <% n = masuk %>
          <% end %>
        <% end %>
    </tbody>
</table>

app/views/admin/books/show.html.erb
<div class="page-header">
    <h3>Data Wisuda Tahun <%= @profile.tahun_wisuda %></h3>
</div>
<% Concentration.find(:all).each do |konsentrasi| %>
  <% if Profile.where(:approved => true).where("concentration_id = ?", "#{konsentrasi.id}").where("tahun_wisuda = ?", "#{@profile.tahun_wisuda}").size != 0 %>
    <h5><%= konsentrasi.title %> : <%= Profile.where(:approved => true).where("concentration_id = ?", "#{konsentrasi.id}").where("tahun_wisuda = ?", "#{@profile.tahun_wisuda}").size %> Mahasiswa</h5>
    <style>
        .table-borderless td,
        .table-borderless th {
            border: 0;
            padding: 0;
            valign: top;
        }
    </style>
    <table class="table table-bordered responsive datatables">
        <thead>
            <tr>
                <th class="span11">Data Wisuda</th>
                <th class="span1">Foto</th>
            </tr>
        </thead>
        <tbody>
            <% Profile.where(:approved => true).where("concentration_id = ?", "#{konsentrasi.id}").where("tahun_wisuda = ?", "#{@profile.tahun_wisuda}").order("nim ASC").each do |x| %>
              <tr>
                  <td class="span12">
                      <table class='table-borderless'>
                          <tr><td width="22%">Nama Lengkap&nbsp;&nbsp;</td><td>&nbsp;&nbsp;:&nbsp;&nbsp;</td><td width="78%"><span style="text-transform: uppercase;"><%= x.nama %></span></td></tr> 
                          <tr><td>Tempat /Tanggal Lahir&nbsp;&nbsp;</td><td>&nbsp;&nbsp;:&nbsp;&nbsp;</td><td><%= x.tempat_lahir %><% unless x.tanggal_lahir.nil? || x.tanggal_lahir == "" %>, <%= indonesia_date((x.tanggal_lahir).to_date) %> <% end %></td></tr> 
                          <tr><td>NIM&nbsp;&nbsp;</td><td>&nbsp;&nbsp;:&nbsp;&nbsp;</td><td><%= x.nim %></td></tr> 
                          <tr><td>Konsentrasi&nbsp;&nbsp;</td><td>&nbsp;&nbsp;:&nbsp;&nbsp;</td><td><%= x.concentration.title %></td></tr> 
                          <tr><td>Keahlian&nbsp;&nbsp;</td><td>&nbsp;&nbsp;:&nbsp;&nbsp;</td><td><%= x.keahlian %></td></tr> 
                          <tr><td>IPK&nbsp;&nbsp;</td><td>&nbsp;&nbsp;:&nbsp;&nbsp;</td><td><% if x.nilai_lta == "" %>0.0<% else %><%= x.ipka %><% end %></td></tr> 
                          <tr><td>Nama Orang Tua&nbsp;&nbsp;</td><td>&nbsp;&nbsp;:&nbsp;&nbsp;</td><td><%= x.ortu %></td></tr> 
                          <tr><td>Alamat Asal&nbsp;&nbsp;</td><td>&nbsp;&nbsp;:&nbsp;&nbsp;</td><td><%= x.alamat_rumah %></td></tr> 
                          <tr><td>Nomor Telepon&nbsp;&nbsp;</td><td>&nbsp;&nbsp;:&nbsp;&nbsp;</td><td><%= x.nomor_telp %></td></tr> 
                          <tr><td>Lokasi PKL&nbsp;&nbsp;</td><td>&nbsp;&nbsp;:&nbsp;&nbsp;</td><td><%= x.tempat_pkl %></td></tr> 
                          <tr><td>Judul LTA&nbsp;&nbsp;</td><td>&nbsp;&nbsp;:&nbsp;&nbsp;</td><td><%= x.judul_ta %></td></tr> 
                      </table>
                      <br />
                  </td>
                  <td  class="span1">
          <center>
              <%= image_tag avatar_url(x.email_avatar, 100), :class => "img-rounded" %><br/>
              <h3 style="color: lightgray;">#<%= ("#{(x.nim).split('')[4]}#{(x.nim).split('')[5]}#{(x.nim).split('')[6]}#{(x.nim).split('')[7]}").to_i %></h3>
          </center>
      </td>
      </tr>
    <% end %>
    </tbody>
    </table>
    <br />
  <% end %>
<% end %>