config/routes.rb
TracerStudy::Application.routes.draw do
  

  resource :passwords  
  #  get "passwords/edit"
  #  get "passwords/update"
  get "dashboards/index"

  resource :profiles
  resources :profiles
  resources :dashboards
  authenticated :user do
    root :to => 'dashboards#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  #  as :member do
  #    get 'password/edit' => 'devise/registrations#edit', :as => 'member_edit_password'   
  #    put 'password' => 'devise/registrations#update', :as => 'member_user_password'            
  #  end
  resources :users do
    collection do
      get :reset_password
      get :verifikasi
      get :proses
    end
  end
  get "users/:id/reset_password" => "users#reset_password", :as => 'user_reset_password'
  #get "users/verifikasi" => "users#verifikasi", :as => 'user_verifikasi_alumni'
  post "users/proses" => "users#proses", :as => 'user_proses'
  get "admin/users/:id/reset_password" => "admin/users#reset_password", :as => 'admin_user_reset_password'
  get "admin/users/:id/aproval" => "admin/users#aproval", :as => 'admin_user_aproval'
  get "admin/users/:id/unaproval" => "admin/users#unaproval", :as => 'admin_user_unaproval'
  match 'profiles/edit' => 'profiles#edit', :via => :get
  
  namespace :admin do
    resources :dashboards 
    resources :profiles
    resources :cards
    resources :books do
      collection do
        get :download
      end
    end
    resources :users do
      collection do
        get :reset_password
        get :aproval
        get :all_approval
        get :unaproval
      end
    end
  end
  get "admin/books/download/:id" => "admin/books#download", :as => 'admin_book_download_xls'
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :login, :username, :name, :email, :password, :password_confirmation, :approved, :remember_me, :nomor_urut, :profile_attributes
  has_one :profile, :dependent => :destroy
  accepts_nested_attributes_for :profile, :reject_if => proc { |attributes| attributes['nama'].blank? }
  validates_associated :profile
  after_create :default_role
  attr_accessor :login
  validates_presence_of :username,
    :presence => true,
    :uniqueness => {
    :case_sensitive => false
  }, :message => 'Tidak Boleh Kosong.'
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end
  
  
  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end

  private
  
  def default_role
    add_role(:user)
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    terakhir = "%04d" % (User.includes(:roles).where("roles.name = 'user'").where(:approved => true).size).to_s
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.includes(:roles).where("roles.name = 'user'")
    @usersfalse = User.includes(:roles).where("roles.name = 'user'").where(:approved => false)
    @userstrue = User.includes(:roles).where("roles.name = 'user'").where(:approved => true)
    @userslast = User.includes(:roles).where("roles.name = 'user'").where(:approved => true).limit(1).where("users.nomor_urut = ?", "#{terakhir}")
  end
  
  def new
    authorize! :new, @user, :message => 'Not authorized as an administrator.'
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end
  
  def edit
    authorize! :new, @user, :message => 'Not authorized as an administrator.'
    @profile = Profile.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    @user.nomor_urut = (@user.profile.nia).split(".")[3]
    if @user.update_attributes(params[:user], :as => :admin)
      @user.profile.email = @user.email
      @user.profile.nia = "#{@user.profile.concentration.value}.#{(@user.profile.tahun_masuk).strftime("%y")}.#{(@user.profile.tgl_lulus).to_date.strftime("%m%y")}.#{@user.nomor_urut}"
      @user.profile.save
      redirect_to admin_users_path, :notice => "User updated."
    else
      redirect_to admin_users_path, :alert => "Unable to update user."
    end
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Successfully created User." 
      redirect_to admin_users_path
    else
      redirect_to admin_users_path
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to admin_users_path, :notice => "User deleted."
    else
      redirect_to admin_users_path, :notice => "Can't delete yourself."
    end
  end
  
  def reset_password
    user = User.find(params[:id])
    generated_password = '123456'
    user.password = generated_password
    user.password_confirmation = generated_password
    if user.save
      UserMailer.reset_password(user, generated_password).deliver
      redirect_to admin_users_path, :notice => "Password Reset Successful."
    end
  end
  
  def aproval
    user = User.find(params[:id])
    if user.approved == false
      user.approved = true
      user.username = "#{user.profile.concentration.value}.#{(user.profile.tahun_masuk).strftime("%y")}.#{(user.profile.tgl_lulus).to_date.strftime("%m%y")}.""%04d" % (User.includes(:roles).where("roles.name = 'user'").where(:approved => true).size + 1).to_s
      user.nomor_urut = (user.username).split(".")[3]
      user.profile.nia = user.username
      user.profile.tahun_wisuda = ((user.profile.tgl_lulus).to_date).strftime("%Y")
      user.profile.approved = true
      user.save
      UserMailer.approval(user).deliver
    end        
    #@user.update_attributes(:password => '12345678', :password_confirmation => '123456789')
    redirect_to admin_users_path, :notice => "Aproval Successful."
  end
  
  def unaproval
    user = User.find(params[:id])
    if user.approved == true
      user.approved = false
      user.username = user.profile.nim
      user.nomor_urut = ""
      user.profile.nia = user.username
      user.profile.tahun_wisuda = ((user.profile.tgl_lulus).to_date).strftime("%Y")
      user.profile.approved = false
      user.save
      UserMailer.approval(user).deliver
    end        
    #@user.update_attributes(:password => '12345678', :password_confirmation => '123456789')
    redirect_to admin_users_path, :notice => "Unaproval Successful."
  end
  
  def all_approval
    user = User.find_all_by_approved(false)
    user.each do |user_profile|
      if user_profile.approved == false
        user_profile.approved = true
        user_profile.username = "#{user.profile.concentration.value}.#{(user.profile.tahun_masuk).strftime("%y")}.#{(user.profile.tgl_lulus).to_date.strftime("%m%y")}.""%04d" % (User.includes(:roles).where("roles.name = 'user'").where(:approved => true).size + 1).to_s
        user_profile.nomor_urut = (user.username).split(".")[3]
        user_profile.profile.nia = user_profile.username
        user_profile.profile.approved = true
        user_profile.profile.tahun_wisuda = ((user_profile.profile.tgl_lulus).to_date).strftime("%Y")
        user_profile.save
        UserMailer.approval(user_profile).deliver
      end
    end
    redirect_to admin_users_path, :notice => "All Aproval Successful."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.includes(:roles).where("roles.name = 'user'")
  end
  
  def new
    authorize! :new, @user, :message => 'Not authorized as an administrator.'
    @user = User.new
  end

  def show
    if  current_user.profile.blank? == true 
      redirect_to new_profiles_url
    else
      @user = User.find(params[:id])
    end
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Successfully created User." 
      redirect_to users_path
    else
      redirect_to users_path
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
  
  def reset_password
    user = User.find(params[:id])
    user.password = '12345678'
    user.password_confirmation = '12345678'
    user.save
    #@user.update_attributes(:password => '12345678', :password_confirmation => '123456789')
    redirect_to users_path, :notice => "Password Reset Successful."
  end
  
  def aproval
    user = User.find(params[:id])
    user.approved = true
    user.save
    #@user.update_attributes(:password => '12345678', :password_confirmation => '123456789')
    redirect_to users_path, :notice => "Password Reset Successful."
  end
  
  def verifikasi
    
  end
  
  def proses
    size = Profile.where(["nim = ?", params[:nim]]).where(["nama = ?", params[:nama]]).where(["approved = ?", true]).size
    profile = Profile.where(["nim = ?", params[:nim]]).where(["nama = ?", params[:nama]]).where(["approved = ?", true]).first
    generated_password = Devise.friendly_token.first(16)
    if size == 1
      user = User.find(profile.user_id)
      user.password = generated_password
      user.password_confirmation = generated_password
      user.save
      UserMailer.verification(params[:email], user, generated_password).deliver
      redirect_to user_verifikasi_alumni_path, :notice => "NIA dan Password telah dikirim ke email anda"
    elsif size == 0
      redirect_to user_verifikasi_alumni_path, :notice => "Maaf data yang anda maksud belum tersedia"
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="page-header">
<h3>Daftar Pengguna</h3>
</div>
<br />
<table class="table table-bordered responsive datatables">
  <thead>
    <tr>
      <th width="10%">NIM</th>
      <th width="15%">Email</th>
      <th width="10%">Nama Alumni</th>
      <th width="10%">Registered</th>
      <th width="10%">Status</th>
      <th width="7%">Role</th>
      <th width="20%"></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %><%#= link_to user.username, user %></td>
      <td><%= user.email %></td>
      <td><%= user.profile.nama rescue nil %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.approved %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
        <%= link_to("Reset Password", user_reset_password_path(user), :class => 'btn btn-mini') %>
        <%#= link_to("Persetujuan", user_aproval_path(user), :class => 'btn btn-mini') %>
        <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.input :name, :autofocus => true, :label => "Username" %>
  <%= f.input :email, :required => true %>
  <%= f.input :password, :required => true %>
  <%= f.input :password_confirmation, :required => true %>
  <%= f.button :submit, 'Sign up', :class => 'btn-primary' %>
<% end %>

app/views/users/show.html.erb
<div class="page-header">
<h3><%= @user.name %>'s Profile</h3>
</div>
<br/>
<p>Email: <%= @user.email if @user.email %></p>

app/views/users/verifikasi.html.erb
<div class="page-header">
    <h3>Verifikasi Data Alumni</h3>
</div>

<%= form_tag(user_proses_path, :html => {:class => 'form-vertical' }) do %>
  <div class="form-group">
      <label for="exampleInputEmail1">Nomor Induk Mahasiswa (Sesuai Ijazah)</label>
      <%= text_field_tag :nim %>
  </div>
  <div class="form-group">
      <label for="exampleInputEmail1">Nama Mahasiswa (Sesuai Ijazah)</label>
      <%= text_field_tag :nama %>
  </div>
  <div class="form-group">
      <label for="exampleInputEmail1">Email</label>
      <%= text_field_tag :email %>
  </div>
  <%= submit_tag "Verifikasi", :class => "btn btn-primary" %>
<% end %>