config/routes.rb
TracerStudy::Application.routes.draw do
  

  resource :passwords  
  #  get "passwords/edit"
  #  get "passwords/update"
  get "dashboards/index"

  resource :profiles
  resources :profiles
  resources :dashboards
  authenticated :user do
    root :to => 'dashboards#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  #  as :member do
  #    get 'password/edit' => 'devise/registrations#edit', :as => 'member_edit_password'   
  #    put 'password' => 'devise/registrations#update', :as => 'member_user_password'            
  #  end
  resources :users do
    collection do
      get :reset_password
      get :verifikasi
      get :proses
    end
  end
  get "users/:id/reset_password" => "users#reset_password", :as => 'user_reset_password'
  #get "users/verifikasi" => "users#verifikasi", :as => 'user_verifikasi_alumni'
  post "users/proses" => "users#proses", :as => 'user_proses'
  get "admin/users/:id/reset_password" => "admin/users#reset_password", :as => 'admin_user_reset_password'
  get "admin/users/:id/aproval" => "admin/users#aproval", :as => 'admin_user_aproval'
  get "admin/users/:id/unaproval" => "admin/users#unaproval", :as => 'admin_user_unaproval'
  match 'profiles/edit' => 'profiles#edit', :via => :get
  
  namespace :admin do
    resources :dashboards 
    resources :profiles
    resources :cards
    resources :books do
      collection do
        get :download
      end
    end
    resources :users do
      collection do
        get :reset_password
        get :aproval
        get :all_approval
        get :unaproval
      end
    end
  end
  get "admin/books/download/:id" => "admin/books#download", :as => 'admin_book_download_xls'
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :login, :username, :name, :email, :password, :password_confirmation, :approved, :remember_me, :nomor_urut, :profile_attributes
  has_one :profile, :dependent => :destroy
  accepts_nested_attributes_for :profile, :reject_if => proc { |attributes| attributes['nama'].blank? }
  validates_associated :profile
  after_create :default_role
  attr_accessor :login
  validates_presence_of :username,
    :presence => true,
    :uniqueness => {
    :case_sensitive => false
  }, :message => 'Tidak Boleh Kosong.'
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end
  
  
  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end

  private
  
  def default_role
    add_role(:user)
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    terakhir = "%04d" % (User.includes(:roles).where("roles.name = 'user'").where(:approved => true).size).to_s
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.includes(:roles).where("roles.name = 'user'")
    @usersfalse = User.includes(:roles).where("roles.name = 'user'").where(:approved => false)
    @userstrue = User.includes(:roles).where("roles.name = 'user'").where(:approved => true)
    @userslast = User.includes(:roles).where("roles.name = 'user'").where(:approved => true).limit(1).where("users.nomor_urut = ?", "#{terakhir}")
  end
  
  def new
    authorize! :new, @user, :message => 'Not authorized as an administrator.'
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end
  
  def edit
    authorize! :new, @user, :message => 'Not authorized as an administrator.'
    @profile = Profile.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    @user.nomor_urut = (@user.profile.nia).split(".")[3]
    if @user.update_attributes(params[:user], :as => :admin)
      @user.profile.email = @user.email
      @user.profile.nia = "#{@user.profile.concentration.value}.#{(@user.profile.tahun_masuk).strftime("%y")}.#{(@user.profile.tgl_lulus).to_date.strftime("%m%y")}.#{@user.nomor_urut}"
      @user.profile.save
      redirect_to admin_users_path, :notice => "User updated."
    else
      redirect_to admin_users_path, :alert => "Unable to update user."
    end
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Successfully created User." 
      redirect_to admin_users_path
    else
      redirect_to admin_users_path
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to admin_users_path, :notice => "User deleted."
    else
      redirect_to admin_users_path, :notice => "Can't delete yourself."
    end
  end
  
  def reset_password
    user = User.find(params[:id])
    generated_password = '123456'
    user.password = generated_password
    user.password_confirmation = generated_password
    if user.save
      UserMailer.reset_password(user, generated_password).deliver
      redirect_to admin_users_path, :notice => "Password Reset Successful."
    end
  end
  
  def aproval
    user = User.find(params[:id])
    if user.approved == false
      user.approved = true
      user.username = "#{user.profile.concentration.value}.#{(user.profile.tahun_masuk).strftime("%y")}.#{(user.profile.tgl_lulus).to_date.strftime("%m%y")}.""%04d" % (User.includes(:roles).where("roles.name = 'user'").where(:approved => true).size + 1).to_s
      user.nomor_urut = (user.username).split(".")[3]
      user.profile.nia = user.username
      user.profile.tahun_wisuda = ((user.profile.tgl_lulus).to_date).strftime("%Y")
      user.profile.approved = true
      user.save
      UserMailer.approval(user).deliver
    end        
    #@user.update_attributes(:password => '12345678', :password_confirmation => '123456789')
    redirect_to admin_users_path, :notice => "Aproval Successful."
  end
  
  def unaproval
    user = User.find(params[:id])
    if user.approved == true
      user.approved = false
      user.username = user.profile.nim
      user.nomor_urut = ""
      user.profile.nia = user.username
      user.profile.tahun_wisuda = ((user.profile.tgl_lulus).to_date).strftime("%Y")
      user.profile.approved = false
      user.save
      UserMailer.approval(user).deliver
    end        
    #@user.update_attributes(:password => '12345678', :password_confirmation => '123456789')
    redirect_to admin_users_path, :notice => "Unaproval Successful."
  end
  
  def all_approval
    user = User.find_all_by_approved(false)
    user.each do |user_profile|
      if user_profile.approved == false
        user_profile.approved = true
        user_profile.username = "#{user.profile.concentration.value}.#{(user.profile.tahun_masuk).strftime("%y")}.#{(user.profile.tgl_lulus).to_date.strftime("%m%y")}.""%04d" % (User.includes(:roles).where("roles.name = 'user'").where(:approved => true).size + 1).to_s
        user_profile.nomor_urut = (user.username).split(".")[3]
        user_profile.profile.nia = user_profile.username
        user_profile.profile.approved = true
        user_profile.profile.tahun_wisuda = ((user_profile.profile.tgl_lulus).to_date).strftime("%Y")
        user_profile.save
        UserMailer.approval(user_profile).deliver
      end
    end
    redirect_to admin_users_path, :notice => "All Aproval Successful."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.includes(:roles).where("roles.name = 'user'")
  end
  
  def new
    authorize! :new, @user, :message => 'Not authorized as an administrator.'
    @user = User.new
  end

  def show
    if  current_user.profile.blank? == true 
      redirect_to new_profiles_url
    else
      @user = User.find(params[:id])
    end
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Successfully created User." 
      redirect_to users_path
    else
      redirect_to users_path
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
  
  def reset_password
    user = User.find(params[:id])
    user.password = '12345678'
    user.password_confirmation = '12345678'
    user.save
    #@user.update_attributes(:password => '12345678', :password_confirmation => '123456789')
    redirect_to users_path, :notice => "Password Reset Successful."
  end
  
  def aproval
    user = User.find(params[:id])
    user.approved = true
    user.save
    #@user.update_attributes(:password => '12345678', :password_confirmation => '123456789')
    redirect_to users_path, :notice => "Password Reset Successful."
  end
  
  def verifikasi
    
  end
  
  def proses
    size = Profile.where(["nim = ?", params[:nim]]).where(["nama = ?", params[:nama]]).where(["approved = ?", true]).size
    profile = Profile.where(["nim = ?", params[:nim]]).where(["nama = ?", params[:nama]]).where(["approved = ?", true]).first
    generated_password = Devise.friendly_token.first(16)
    if size == 1
      user = User.find(profile.user_id)
      user.password = generated_password
      user.password_confirmation = generated_password
      user.save
      UserMailer.verification(params[:email], user, generated_password).deliver
      redirect_to user_verifikasi_alumni_path, :notice => "NIA dan Password telah dikirim ke email anda"
    elsif size == 0
      redirect_to user_verifikasi_alumni_path, :notice => "Maaf data yang anda maksud belum tersedia"
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<script>
  $(document).ready(function () {
      $('#profile_jmh_bobot_x_kredit').keyup(function () {
          if ($('#profile_jmh_bobot_x_kredit').val() != "" && $('#profile_sks_ditempuh').val() != "")
          {
              var bobotxkredit = parseFloat($('#profile_jmh_bobot_x_kredit').val()) || 0;
              var sks = parseFloat($('#profile_sks_ditempuh').val()) || 0;
              var total = bobotxkredit / sks;
              var nilailta = parseFloat($('#profile_nilai_lta').val()) || 0;
              var total1 = (bobotxkredit + (nilailta * 5)) / 120;
              $('#profile_ipka').val(total1.toFixed(2));
              $('#profile_ipka_view').val(total1.toFixed(2));
              $('#profile_ipk').val(total.toFixed(2));
              $('#profile_ipk_view').val(total.toFixed(2));
          }
      });
      $('#profile_sks_ditempuh').keyup(function () {
          if ($('#profile_jmh_bobot_x_kredit').val() != "" && $('#profile_sks_ditempuh').val() != "")
          {
              var bobotxkredit = parseFloat($('#profile_jmh_bobot_x_kredit').val()) || 0;
              var sks = parseFloat($('#profile_sks_ditempuh').val()) || 0;
              var total = bobotxkredit / sks;
              $('#profile_ipk_view').val(total.toFixed(2));
              $('#profile_ipk').val(total.toFixed(2));
          }
      });
      $('#profile_nilai_lta').keyup(function () {
          if ($('#profile_jmh_bobot_x_kredit').val() != "" && $('#profile_nilai_lta').val() != "")
          {
              var bobotxkredit = parseFloat($('#profile_jmh_bobot_x_kredit').val()) || 0;
              var nilailta = parseFloat($('#profile_nilai_lta').val()) || 0;
              var total = (bobotxkredit + (nilailta * 5)) / 120;
              $('#profile_ipka_view').val(total.toFixed(2));
              $('#profile_ipka').val(total.toFixed(2));
          }
      });
  });
</script>
<%= simple_form_for (@profile) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
      <div class="row">
          <div class="span4">
              <%= f.input :nia, disabled: true, :label => "Nomor Induk Alumni" %>
              <%= f.input :nim, :label => "Nomor Induk Mahasiswa" %>
              <%= f.input :nama %>
              <%= f.input :concentration_id, collection: Concentration.all, label_method: :title, value_method: :id, label: "Konsentrasi", include_blank: false %>
              <%= f.input :tahun_masuk, as: :date, :label => "Angkatan", start_year: Date.today.year,
                end_year: Date.today.year - 15, order: [:year] %>
              <%= f.input :tgl_lulus, :label => "Tanggal Lulus", :input_html => { :class => 'datepicker' } %>
              <%= f.input :email, :input_html => { :value => @profile.user.email } %>
              <%= f.input :email_avatar %>
              <%= f.input :tempat_lahir %>
              <%= f.input :tanggal_lahir, :input_html => { :class => 'datepicker' } %>
              <%= f.input :alamat_rumah, :input_html => {:rows => 5}, :label => "Alamat Rumah"  %>

          </div>
          <div class="span4">
              <%= f.input :ortu, :label => "Nama Orang Tua" %>
              <%= f.input :nomor_HP, :label => "Nomor Handphone" %>
              <%= f.input :keahlian, :label => "Keahlian" %>
  <%#= f.input :jmh_bobot_x_kredit, :label => "Jumlah Bobot x Kredit" %>
  <%#= f.input :sks_ditempuh, disabled: true , :input_html => { :value => '115' }, :label => "SKS Telah di Tempuh" %>
  <%#= f.input :sks_ditempuh, :as => :hidden, :input_html => { :value => '115' }, :label => "SKS Telah di Tempuh" %>
  <%#= f.input :ipk_view, disabled: true, :input_html => { :value => number_with_precision(@profile.ipk, precision: 2) }, :label => "Index Prestasi Komulatif" %>
  <%#= f.input :ipk, :as => :hidden, :label => "Index Prestasi Komulatif" %>
  <%#= f.input :nilai_lta, :label => "Nilai LTA" %>
  <%#= f.input :ipka_view, disabled: true, :input_html => { :value => @profile.ipka }, :label => "Index Prestasi Akhir" %>
              <%= f.input :ipka, :label => "Index Prestasi" %>
              <%= f.input :no_wa, :label => "Nomor Whatapps" %>
              <%= f.input :nomor_telp, :label => "Nomor Telepon" %>
              <%= f.input :pinbb, :label => "PIN Blackberry" %>
              <%= f.input :facebook, :label => "Facebook" %>
              <%= f.input :blog, :label => "Blog" %>
              <%= f.input :web, :label => "Website" %>
              <%= f.input :tempat_pkl, :input_html => {:width => 30}, :label => "Tempat PKL" %>
              <%= f.input :judul_ta, :input_html => {:rows => 3}, :label => "Judul Tugas Akhir" %>
          </div>
          <div class="span4">
              <%= f.input :nama_instansi_first, :label => "Nama Instansi Pertama Kerja" %>
              <%= f.input :jabatan_first, :label => "Jabatan Pertama Kerja" %>
              <%= f.input :tanggal_masuk_kerja_first, :label => "Tanggal Pertama Kerja", :input_html => { :class => 'datepicker' } %>
              <%= f.input :nama_instansi_last, :label => "Nama Instansi Berikutnya" %>
              <%= f.input :jabatan_last, :label => "Jabatan Berikutnya" %>
              <%= f.input :tanggal_masuk_kerja_last, :label => "Tanggal Kerja Berikutnya", :input_html => { :class => 'datepicker' } %>
          </div>
      </div>
  </div>

  <div class="form-actions">
      <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
    <%= simple_form_for user, :url => admin_user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
      <div class="modal-header">
          <a class="close" data-dismiss="modal">&#215;</a>
          <h3>Change Role</h3>
      </div>
      <div class="modal-body">
          <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
      </div>
      <div class="modal-footer">
          <%= f.submit "Change Role", :class => "btn" %>
          <a class="btn" data-dismiss="modal" href="#">Close</a>
      </div>
    <% end %>
</div>
<style type="text/css" media="all">
    .papersetengahA4{
        background-color: White;
        border: 1px dashed #66ff66;
        font-family: "Trebuchet MS",Arial,Tahoma,Verdana;
        height: 55mm;
        padding: 1px;
        width: 85mm;
    }
    .table-borderless td,
    .table-borderless th {
        border: 0;
        padding: 0;
        valign: top;
    }
</style>
<script language="javascript" type="text/javascript">
  function printOut() {
      var getDisplay = document.getElementById("printarea").innerHTML;

      var setPrint = window.open("", "printed", "width=500,height=200,menubar=0,scrollbars=1,statusbar=0");
      setPrint.document.open();
      setPrint.document.write('<html>');
      setPrint.document.write('<head>');
      setPrint.document.write('<meta http-equiv="pragma" content="no-cache">');
      setPrint.document.write("<title>KARTU ALUMNI</title>");
      //setPrint.document.write('<link href="include/cetakkumulatif.css" rel="stylesheet" type="text/css">');
      setPrint.document.write('</head>');
      setPrint.document.write('<body onLoad="self.print()">');
      setPrint.document.write(getDisplay);
      setPrint.document.write('</body></html>');
      setPrint.document.close();
      window.close("", "printed");
  }
</script>
<div id="card-options-<%= user.id %>" class="modal" style="display: none;">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&#215;</a>
        <h3>Cetak Kartu Alumni</h3>
    </div>
    <div class="modal-body">
        
    </div>
    <div class="modal-footer">
        <input class="btn" data-dismiss="modal" id="btncetakkhs" value="Cetak" onclick="printOut();" type="button">
        <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
</div>

app/views/admin/users/edit.html.erb
<div class="page-header">
  <h3>Perbaiki Penguna</h3>
</div>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<div class="page-header">
    <h3>Data Alumni</h3>
</div>
<table>
    <tr>
        <td class="span4">Nomor Alumni Selanjutnya</td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;</td>
        <td><%= "%04d" % (User.includes(:roles).where("roles.name = 'user'").where(:approved => true).size + 1).to_s %></td>
    </tr>
</table>
<br />
<table class="table table-bordered responsive datatables">
    <thead>
        <tr>
            <th class="span2">NIM</th>
            <th class="span2">NIA</th>
            <th class="span4">Email</th>
            <th class="span5">Nama Alumni</th>
            <th class="span2">Registered</th>
            <th class="span1">Status</th>
            <th class="span2"></th>
        </tr>
    </thead>
    <tbody>
        <% @userslast.each do |user| %>
          <tr>
              <td><%= user.profile.nim rescue nil %></td>
              <td><%= user.profile.nia %></td>
              <td><%= user.email %></td>
              <td><%= user.profile.nama rescue nil %></td>
              <td><%= user.created_at.to_date %></td>
              <td>
                  <% if user.approved == true %>
                    <i class="icon-ok-sign"></i>
                  <% elsif user.approved == false %>
                    <i class="icon-remove-sign"></i>
                  <% end %>
              </td>
              <td>
                  <!--<%#*<a data-toggle="modal" href="#role-options-<%= user.id %>" title="Change Role"><i class="icon-certificate"></i></a>%>
  <%#= render user %>-->
  <%#= link_to '<i class="icon-wrench"></i>'.html_safe, admin_user_reset_password_path(user), 'data-placement' => "top",  'title' => "Reset Password" %>
                  <%= link_to '<i class="icon-thumbs-down"></i>'.html_safe, admin_user_unaproval_path(user), 'data-placement' => "top",  'title' => "Unapprove" %>
  <%#= link_to '<i class="icon-remove"></i>'.html_safe, admin_user_path(user), :data => { :confirm => "Are you sure?" }, 'data-placement' => "top",  'title' => "Delete" unless user == current_user %>
  <%#= link_to '<i class="icon-edit"></i>'.html_safe, edit_admin_user_path(user.profile.id), 'data-placement' => "top",  'title' => "Edit Data" unless user == current_user %>
              </td>
          </tr>
        <% end %>
    </tbody>
</table>
<br/>
<div>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#belum-aktif" aria-controls="home" role="tab" data-toggle="tab">Data Belum Aktif <span class="badge"><%= @usersfalse.size %></span></a></li>
        <li role="presentation"><a href="#sudah-aktif" aria-controls="profile" role="tab" data-toggle="tab">Data Sudah Aktif <span class="badge"><%= @userstrue.size %></span></a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="belum-aktif">
            <% link_to("Setujui Semua", all_approval_admin_users_path, :class => 'btn btn-primary') %>
            <table class="table table-bordered responsive datatables">
                <thead>
                    <tr>
                        <th class="span2">NIM</th>
                        <th class="span4">Email</th>
                        <th class="span5">Nama Alumni</th>
                        <th class="span2">Registered</th>
                        <th class="span2"></th>
                    </tr>
                </thead>
                <tbody>
                    <% @usersfalse.each do |user| %>
                      <tr>
                          <td><%= user.profile.nim %></td>
                          <td><%= user.email %></td>
                          <td><%= user.profile.nama rescue nil %></td>
                          <td><%= user.created_at.to_date %></td>
                          <td>
                              <a data-toggle="modal" href="#role-options-<%= user.id %>" title="Change Role"><i class="icon-certificate"></i></a>
                              <%= link_to '<i class="icon-wrench"></i>'.html_safe, admin_user_reset_password_path(user), 'data-placement' => "top",  'title' => "Reset Password" %>
                              <%= link_to '<i class="icon-thumbs-up"></i>'.html_safe, admin_user_aproval_path(user), 'data-placement' => "top",  'title' => "Approve" %>
  <%#= link_to '<i class="icon-remove"></i>'.html_safe, admin_user_path(user), :data => { :confirm => "Are you sure?" }, 'data-placement' => "top",  'title' => "Delete" unless user == current_user %>
                              <%= link_to '<i class="icon-edit"></i>'.html_safe, edit_admin_user_path(user.profile.id), 'data-placement' => "top",  'title' => "Edit Data" unless user == current_user %>
                          </td>
                      </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div role="tabpanel" class="tab-pane" id="sudah-aktif">
            <table class="table table-bordered responsive datatables">
                <thead>
                    <tr>
                        <th class="span2">NIM</th>
                        <th class="span2">NIA</th>
                        <th class="span4">Email</th>
                        <th class="span5">Nama Alumni</th>
                        <th class="span2">Registered</th>
                        <th class="span2"></th>
                    </tr>
                </thead>
                <tbody>
                    <% @userstrue.each do |user| %>
                      <tr>
                          <td><%= user.profile.nim %></td>
                          <td><%= user.profile.nia %></td>
                          <td><%= user.email %></td>
                          <td><%= user.profile.nama rescue nil %></td>
                          <td><%= user.created_at.to_date %></td>
                          <td>
                              <a data-toggle="modal" href="#role-options-<%= user.id %>" title="Change Role"><i class="icon-certificate"></i></a>
                                  <%= link_to '<i class="icon-wrench"></i>'.html_safe, admin_user_reset_password_path(user), 'data-placement' => "top",  'title' => "Reset Password" %>
                                  <%#= link_to '<i class="icon-thumbs-up"></i>'.html_safe, admin_user_aproval_path(user), 'data-placement' => "top",  'title' => "Approve" %>
  <%#= link_to '<i class="icon-remove"></i>'.html_safe, admin_user_path(user), :data => { :confirm => "Are you sure?" }, 'data-placement' => "top",  'title' => "Delete" unless user == current_user %>
                                  <%= link_to '<i class="icon-edit"></i>'.html_safe, edit_admin_user_path(user.profile.id), 'data-placement' => "top",  'title' => "Edit Data" unless user == current_user %>
                          </td>
                      </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>

</div>

app/views/admin/users/new.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.input :name, :autofocus => true, :label => "Username" %>
  <%= f.input :email, :required => true %>
  <%= f.input :password, :required => true %>
  <%= f.input :password_confirmation, :required => true %>
  <%= f.button :submit, 'Sign up', :class => 'btn-primary' %>
<% end %>

app/views/admin/users/show.html.erb
<div class="page-header">
<h3><%= @user.name %>'s Profile</h3>
</div>
<br/>
<p>Email: <%= @user.email if @user.email %></p>