config/routes.rb
TracerStudy::Application.routes.draw do
  

  resource :passwords  
  #  get "passwords/edit"
  #  get "passwords/update"
  get "dashboards/index"

  resource :profiles
  resources :profiles
  resources :dashboards
  authenticated :user do
    root :to => 'dashboards#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  #  as :member do
  #    get 'password/edit' => 'devise/registrations#edit', :as => 'member_edit_password'   
  #    put 'password' => 'devise/registrations#update', :as => 'member_user_password'            
  #  end
  resources :users do
    collection do
      get :reset_password
      get :verifikasi
      get :proses
    end
  end
  get "users/:id/reset_password" => "users#reset_password", :as => 'user_reset_password'
  #get "users/verifikasi" => "users#verifikasi", :as => 'user_verifikasi_alumni'
  post "users/proses" => "users#proses", :as => 'user_proses'
  get "admin/users/:id/reset_password" => "admin/users#reset_password", :as => 'admin_user_reset_password'
  get "admin/users/:id/aproval" => "admin/users#aproval", :as => 'admin_user_aproval'
  get "admin/users/:id/unaproval" => "admin/users#unaproval", :as => 'admin_user_unaproval'
  match 'profiles/edit' => 'profiles#edit', :via => :get
  
  namespace :admin do
    resources :dashboards 
    resources :profiles
    resources :cards
    resources :books do
      collection do
        get :download
      end
    end
    resources :users do
      collection do
        get :reset_password
        get :aproval
        get :all_approval
        get :unaproval
      end
    end
  end
  get "admin/books/download/:id" => "admin/books#download", :as => 'admin_book_download_xls'
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Tracer Study AMA Yogyakarta", root_path, :class => 'brand' %>
<ul class="nav">
    <% if user_signed_in? %>
      <%#*<li>%>
          <%#= link_to 'Ganti Password', edit_password_path %>
      <%#*</li>%>
      <% if current_user.has_role? :admin %>
        <li>
            <%= link_to 'Data Alumni', admin_users_path %>
        </li>
        <li>
            <%= link_to 'Data Wisuda', admin_books_path %>
        </li>
      <% elsif current_user.has_role? :user %>
        <li>
            <%= link_to 'Perbaiki Profile', profiles_edit_path %>
        </li>
        <li>
            <%= link_to 'Ganti Password', edit_passwords_path %>
        </li>
      <% end %>
    <% else %>
      <li>
          <%= link_to 'Daftar', new_user_registration_path unless user_signed_in? %>
      </li>
    <% end %>
    <% if user_signed_in? %>
      <li>
          <%= link_to 'Keluar', destroy_user_session_path, :method=>'delete' %>
      </li>
    <% else %>
      <li>
          <%= link_to 'Masuk', new_user_session_path %>
      </li>
      <!--<li>
          <%#= link_to 'Verifikasi Data Alumni', verifikasi_users_path %>
      </li>-->
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tracer Study AMA Yogyakarta" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Tracer Study AMA Yogyakarta" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <br/>
          <br/>
          <footer>
              <p>&copy; Tracer Study AMA Yogyakarta 2016 - Developer By Andry Sucipto</p>
          </footer>
        </div>
      </div> <!--! end of .container -->
      
    </div> <!--! end of #main -->
  </body>
</html>